name: 'financial_exposure_poc'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'financial_exposure_poc'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

# DBT cloud specific configuration
dbt-cloud:
    project-id: 70471823484533

# Snapshot configuration
snapshots:
  financial_exposure_poc:
    +target_schema: snapshots_raw

# Seed configuration
seeds:
  financial_exposure_poc:
    raw:
      +schema: raw
      +quote_columns: true


# Models configuration
models:
  financial_exposure_poc:
    01_bronze:
      +materialized: view
      +schema: bronze      
      

    02_silver:
      raw_vault:
        +materialized: incremental
        +schema: silver_raw_vault
      business_vault:
        +materialized: view
        +schema: silver_business_vault

    03_gold:
      +materialized: table
      +schema: gold

# Test configuration
tests:
  +schema: 'test_failures'
  
# Documentation
docs-paths: ["docs"]

