name: 'financial_exposure_poc'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'financial_exposure_poc'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

# DBT cloud specific configuration
dbt-cloud:
    project-id: 70471823484533

# Snapshot configuration
snapshots:
  financial_exposure_poc:
    +target_schema: snapshots_raw

# Seed configuration
seeds:
  financial_exposure_poc:
    raw:
      +schema: raw
      +quote_columns: true

# Setting environment variables
vars:
  env_database_map:
    DEV: "DEV_EDFR_NA_STG"
    QUAL: "DEV_EDFR_NA_DWH"
    PROD: "DEV_EDFR_NA_DMT"


# Models configuration
models:
  financial_exposure_poc:
    00_source:
      +materialized: view
      +database: "{{ var('env_database_map')[target.name] }}"
      +schema: bronze

    01_staging:
      +materialized: view
      +database: "{{ var('env_database_map')[target.name] }}"
      +schema: bronze

    02_silver:
      raw_vault:
        +materialized: incremental
        +database: "{{ var('env_database_map')[target.name] }}"
        +schema: silver_raw_vault
      business_vault:
        +materialized: view
        +database: "{{ var('env_database_map')[target.name] }}"
        +schema: silver_business_vault

    03_gold:
      +materialized: table
      +database: "{{ var('env_database_map')[target.name] }}"
      +schema: gold

# Test configuration
tests:
  financial_exposure_poc:
    +store_failures: true
    +schema: test_failures

# Documentation
docs-paths: ["docs"]

